# Hello Numpy Array 

In [1]:
import numpy as np
print(np.__version__)

1.26.4


In [4]:
# 配列
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

[[[[[1 2 3 4]]]]]


In [10]:
import numpy as np
arr = np.array([1, 2, 3])
print(arr[1])

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2
2nd element on 1st row:  2


In [4]:
# numpy slice array

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
x = arr[4:]

print(arr[1:5])
print(x)
print(arr[-3:-1])
print(arr.dtype)

[2 3 4 5]
[5 6 7]
[5 6]
int32


In [8]:
# view と copy 
arr = np.array([1, 2, 3, 4, 5, 6, 7])
v = arr.view()
c = arr.copy()

c[0] = 100 #copyだからarrには影響でない
v[0] = 200 #参照だからarrに影響でる
print(arr[0])

print(arr.base)
print(c.base)
print(v.base)

200
None
None
[200   2   3   4   5   6   7]


In [15]:
# shpae of nparray
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

# reshpae に-1 指定すると1次元配列になる
arr.reshape(-1)
print(arr)

(2, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [16]:
# ループ処理
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [18]:
# 配列の結合と分割
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[1 2 3 4 5 6]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) # 値が4の要素のリストが返ってくる
print(x)

In [19]:
# sort
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr2 = np.array(["a", "car", "banana"])
print(np.sort(arr2))

[0 1 2 3]
['a' 'banana' 'car']


In [27]:
import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = (arr > 42)
newarr = arr[filter_arr]

print(filter_arr)
print(newarr)
print(t)

[False False  True  True]
[43 44]
(array([0, 1, 2, 3], dtype=int64),)
